default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: blog

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_prod

